### ISSUE TITLE
jdk1.8下xml转object错误

### ISSUE THREAD

**Issue by let5sne** [liyiorg/weixin-popular#114]
java.lang.ClassCastException: weixin.popular.bean.paymch.MchBase$JaxbAccessorM_getAppid_setAppid_java_lang_String cannot be cast to com.sun.xml.internal.bind.v2.runtime.reflect.Accessor
        at com.sun.xml.internal.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.instanciate(OptimizedAccessorFactory.java:190)
        at com.sun.xml.internal.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:129)
        at com.sun.xml.internal.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:388)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:77)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.sun.xml.internal.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:113)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:166)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:488)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:153)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:488)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:305)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:124)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1123)
        at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:462)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
        at weixin.popular.util.XMLConverUtil.convertToObject(XMLConverUtil.java:100)
        at weixin.popular.util.XMLConverUtil.convertToObject(XMLConverUtil.java:62)

**Comment by let5sne** [comment]
我的解决办法是，下载源码
1、去掉jaxb-impl 包依赖 
2、XMLConverUtil 中引入 com.sun.xml.internal.bind.marshaller.CharacterEscapeHandler  代替
出现的问题是
mvn package 通不过因为用了jdk sun 内部包
需要在 pom.xml中 maven-compiler-plugin插件中configuration节点下增加 compilerArguments节点，增加子 配置`	<bootclasspath>${java.home}/lib/rt.jar;${java.home}/lib/jce.jar</bootclasspath>`
以上解决办法适用jdk1.8 且不够优雅

**Comment by let5sne** [comment]
我的解决办法是，下载源码
1、去掉jaxb-impl 包依赖 
2、XMLConverUtil 中引入 com.sun.xml.internal.bind.marshaller.CharacterEscapeHandler  代替
出现的问题是
mvn package 通不过因为用了jdk sun 内部包
需要在 pom.xml中 maven-compiler-plugin插件中configuration节点下增加 compilerArguments节点，增加子 配置`	<bootclasspath>${java.home}/lib/rt.jar;${java.home}/lib/jce.jar</bootclasspath>`
以上解决办法适用jdk1.8 且不够优雅

**Comment by chptx** [comment]
现在最新版支持1.8了么？这个问题好像比较严重

**Comment by liyiorg** [comment]
@let5sne  @chptx 支持1.8 ， 目前我们这边使用1.8 jdk 没有问题，可以使用以下方式排查下。
1、确定IDE 中是否正确指定JDK , 而非JRE 
2、将weixin-popular 在pom 中的依赖位置放到开始位置
